services:
  # fontend:
  #   build:
  #     context: ./frontend_next
  #     dockerfile: Dockerfile # Mặc định là "Dockerfile", có thể bỏ dòng này
  #   container_name: frontend_next
  #   ports:
  #     - "${HOST_FE_PORT}:${CONTAINER_FE_PORT}"
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./frontend_next:/workspace
  #     - /workspace/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   stdin_open: true # Mở terminal trong container
  #   tty: true
  backend:
    build:
      context: ./backend_dotnet/
      dockerfile: Dockerfile # Mặc định là "Dockerfile", có thể bỏ dòng này
    container_name: backend_web
    ports:
      - "${HOST_BE_PORT}:${CONTAINER_BE_PORT}"
    env_file:
      - .env
    volumes:
      - ./backend_dotnet:/workspace
    stdin_open: true
    tty: true
    environment:
      - COMPOSE_BAKE=true

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: db
    env_file:
      - .env
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
    volumes:
      - sqlserver_data:/var/opt/mssql
    environment:
      ACCEPT_EULA: ${DB_ACCEPT_EULA}
      SA_PASSWORD: ${DB_SA_PASSWORD}
      MSSQL_PID: ${DB_MSSQL_PID}
      COMPOSE_BAKE: "true"

volumes:
  sqlserver_data:
